version: '3'
networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}
services: 
    nginx:
        build:
            context: ./nginx
        container_name: mynginx
        ports:
            - 80:80
        volumes:
            - ${WORKSPACE_WEBROOT_VHOST_PATH}:/etc/nginx/conf.d
            - ${WORKSPACE_WEBROOT_PATH}:${CONTAINER_WEBROOT_PATH}
        links:
            - php-fpm
        depends_on:
            - php-fpm
        networks:
            frontend:
                aliases:
                    - test.test.com
            backend:
                aliases:
                    - test.test.com
    php-fpm:
        build:
            context: ./php
            args:
                - WEBROOT_PATH=${CONTAINER_WEBROOT_PATH}
                - PHP_VERSION=${PHP_VERSION}
                - PHPREDIS_VERSION=${PHPREDIS_VERSION}
                - INSTALL_PHPREDIS_EXTENSION=${INSTALL_PHPREDIS_EXTENSION}
                - INSTALL_ZIP_EXTENSION=${INSTALL_ZIP_EXTENSION}
                - INSTALL_BCMATH_EXTENSION=${INSTALL_BCMATH_EXTENSION}
                - INSTALL_MYSQLI_EXTENSION=${INSTALL_MYSQLI_EXTENSION}
                - MONGODB_EXTENSION_VERSION=${MONGODB_EXTENSION_VERSION}
                - INSTALL_MONGODB_EXTENSION=${INSTALL_MONGODB_EXTENSION}
        container_name: myphp
        volumes:
            - ${WORKSPACE_WEBROOT_PATH}:${CONTAINER_WEBROOT_PATH}
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/php_errors.log:/tmp/php_errors.log
        networks:
            - backend
    mysql:
        build:
            context: ./mysql
            args:
                - MYSQL_VERSION=${MYSQL_VERSION}
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${WORKSPACE_TIMEZONE}
        container_name: mysql
        ports:
            - ${LOCAL_MYSQL_PORT}:3306
        volumes:
            - ${LOCAL_MYSQL_DATA_PATH}:/var/lib/mysql
            - ./mysql/my.cnf:/etc/alternatives/my.cnf
            - ./mysql/slow.log:/tmp/slow.log
        networks:
            - backend
    redis:
        build:
            context: ./redis
        container_name: myredis
        ports:
            - ${LOCAL_REDIS_PORT}:6379
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ${LOCAL_REDIS_DATA_PATH}:/data
        networks:
            - backend
